packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': false
  '@scarf/scarf': false
  '@stripe/cli': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@mikro-orm/nestjs@7.1.0'
  - '@nestjs/terminus@12.0.0'
  - '@stripe/cli-darwin-arm64@1.52.1'
  - '@stripe/cli-darwin-x64@1.52.1'
  - '@stripe/cli-linux-arm64@1.52.1'
  - '@stripe/cli-linux-x64@1.52.1'
  - '@stripe/cli-win32-x64@1.52.1'
  - '@stripe/cli@1.52.1'
